# --- 1. EC2NodeClass (Giữ nguyên vì đã tạo thành công) ---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: Bottlerocket
  amiSelectorTerms:
    - alias: bottlerocket@latest
  role: "eks-karpenter-demo-karpenter-node-role"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eks-karpenter-demo"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eks-karpenter-demo"
  tags:
    CreatedBy: "Karpenter"
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default-al
spec:
  amiFamily: AL2023 # <--- Quay về AL2
  amiSelectorTerms:
    - alias: al2023@latest # <--- Để Karpenter tự chọn AMI, không gõ tay nữa
  role: "eks-karpenter-demo-karpenter-node-role"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eks-karpenter-demo"
  securityGroupSelectorTerms:
    - tags:s
        karpenter.sh/discovery: "eks-karpenter-demo"
  tags:
    CreatedBy: "Karpenter"
---
# --- 2. NodePool cho NodeJS (SPOT) ---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: nodejs-spot
spec:
  template:
    metadata:
      labels:
        app: nodejs
        tier: backend
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default-al
      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["c", "m", "t"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["2", "4", "8"]
      taints:
        - key: app
          value: nodejs
          effect: NoSchedule

  limits:
    cpu: 100
  
  # FIX: Cập nhật theo chuẩn mới nhất
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m # Chờ 1 phút rảnh rỗi mới gom node

---
# --- 3. NodePool cho Nginx (ON-DEMAND) ---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: nginx-od
spec:
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["t", "m"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["2", "4"]
      taints:
        - key: app
          value: nginx
          effect: NoSchedule

  limits:
    cpu: 50
  
  # FIX: Cập nhật theo chuẩn mới nhất
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m